config/routes.rb
CsvFilter::Application.routes.draw do
  resources :furnitures

 match "/search" => 'furnitures#search' , via: [:get, :post]

   root :to => 'furnitures#index'

end

app/models/filter_result.rb
class FilterResult < ActiveRecord::Base
   attr_accessible :kind, :height, :emergency_exit, :openable, :filter_id
end

app/models/furniture.rb
class Furniture < ActiveRecord::Base
   attr_accessible :kind, :height, :emergency_exit, :openable
end

app/models/temp.rb
class Temp < ActiveRecord::Base
   attr_accessible :filter_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/furnitures_controller.rb
require 'csv'
class FurnituresController < ApplicationController
  # GET /furnitures
  # GET /furnitures.json
  def index
    @furnitures = Furniture.all
    @temp = Temp.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @furnitures }
    end
  end

  # GET /furnitures/1
  # GET /furnitures/1.json
  def show
    @search_results = FilterResult.where(:filter_id => params[:id])
    @search_results =  @search_results.order("height ASC")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @furniture }
    end
  end

  # GET /furnitures/new
  # GET /furnitures/new.json
  def new
    @furniture = Furniture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @furniture }
    end
  end

  # GET /furnitures/1/edit
  def edit
    @furniture = Furniture.find(params[:id])
  end

  # POST /furnitures
  # POST /furnitures.json
  def create
   
    infile = params[:csv_file].read
    
    CSV.parse(infile) do |row|
      furniture = Furniture.new
      furniture.kind = row[0]
      furniture.height = row[1].to_i
      furniture.emergency_exit = (row[2] == "True" ? true : false)
      furniture.openable =  (row[3] == "True" ? true : false)
      furniture.save
   end
    all_results = Furniture.find(:all)
   
    respond_to do |format|
      if all_results
        format.html { redirect_to furnitures_path, notice: 'Furniture was successfully created.' }
        
      else
        format.html { render action: "new" }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /furnitures/1
  # PUT /furnitures/1.json
  def update
    @furniture = Furniture.find(params[:id])

    respond_to do |format|
      if @furniture.update_attributes(params[:furniture])
        format.html { redirect_to @furniture, notice: 'Furniture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /furnitures/1
  # DELETE /furnitures/1.json
  def destroy
    @furniture = Furniture.find(params[:id])
    @furniture.destroy

    respond_to do |format|
      format.html { redirect_to furnitures_url }
      format.json { head :no_content }
    end
  end
  
  def search
   kind = params[:search]
   results = Furniture.where(kind) 
   @t = Temp.create(:filter_id => 1)
   results.each do |result|
     fr = FilterResult.new
     fr.kind = result.kind
     fr.height= result.height
     fr.emergency_exit= result.emergency_exit
     fr.openable= result.openable
     fr.filter_id = @t.id
     fr.save
  end
   @search_results = FilterResult.where(:filter_id => @t.id)
   @search_results =  @search_results.order("height DESC") if params[:order] == "desc"
   @search_results =  @search_results.order("height ASC") if params[:order] == "asc"
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/views/furnitures/_form.html.erb
<%= form_for(@furniture) do |f| %>
  <% if @furniture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@furniture.errors.count, "error") %> prohibited this furniture from being saved:</h2>

      <ul>
      <% @furniture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/furnitures/edit.html.erb
<h1>Editing furniture</h1>

<%= render 'form' %>

<%= link_to 'Show', @furniture %> |
<%= link_to 'Back', furnitures_path %>

app/views/furnitures/index.html.erb
<% if @furnitures.blank? %>
<h1>Upload CSV</h1>
<%= form_for(Furniture.new, :html => {:multipart => true}) do |f| %>
  <%= file_field_tag "csv_file" %><br/>
  <%= submit_tag("Import") %>
<% end %>

<%else %>
<h1>Search </h1>
      <%= form_tag "/search" do %>
      <textarea name='search'> </textarea>
       <%= select_tag "order", options_for_select([["ascending","asc"],["descending","desc"]]) %>
       <%= submit_tag "search"%>
       <% end %>
<% end %>

Searched Filters Link
<% @temp.each do |p| %>
   <%= link_to p.id,furniture_path(p) %> <br>
<% end %>
</table>

<br />

app/views/furnitures/new.html.erb
<h1>New furniture</h1>

<%= render 'form' %>

<%= link_to 'Back', furnitures_path %>

app/views/furnitures/search.html.erb
<TABLE border="1">
<TR><TH>Kind<TH>Height<TH>Openable<TH>Emergency Exit
<% @search_results.each do |p| %>
<TR><TD><%= p.kind %><TD><%= p.height %><TD><%= p.openable %><TD><%= p.emergency_exit %>
<% end %>
</TABLE>

app/views/furnitures/show.html.erb
<TABLE border="1">
<TR><TH>Kind<TH>Height<TH>Openable<TH>Emergency Exit
<% @search_results.each do |p| %>
<TR><TD><%= p.kind %><TD><%= p.height %><TD><%= p.openable %><TD><%= p.emergency_exit %>
<% end %>
</TABLE>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvFilter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>